#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Error params format, try: cli CONTAINER COMMAND [OPTIONS]"
    exit 1
fi

dir=$(dirname $(readlink -e $0))

export $(cat ${dir}/.env | grep -v ^# | xargs)

container="${COMPOSE_PROJECT_NAME}_$1"
check=$(docker ps | awk '{print $NF}' | grep -x "$container")

if [ -z "$check" ]; then
    echo "Container $container not found"
    exit 1
fi

#if [ -n "${ECHO_CONTAINER_COMMAND+x}" ] && [ "${ECHO_CONTAINER_COMMAND}" = "true" ]; then
#    echo -en "\033[2m>>> \033[31;2m$1@container\033[0m\033[2m:\033[34;2m$(pwd)\033[0m\033[2m$ $*\033[0m\n"
#fi

shift

docker exec -it $container sh -c "$*"