#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Error params format, try: doctrine-migrations PROJECT [COMMAND] [OPTIONS]"
    exit 1
fi

project=$1

shift

dir=$(dirname $(readlink -e $0))

bash ${dir}/cmd php74 $project "./vendor/bin/doctrine-migrations $*"