#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Error params format, try: export DATABASE"
    exit 1
fi

dir=$(dirname $(readlink -e $0))

bash ${dir}/cmd postgres "cd /var/lib/postgresql/backup && pg_dump $1 -x -U \${POSTGRES_USER} -T 'logging*' -T 'reversions*' -T 'webhooks_logging*' > $1.sql"