#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 5 ]; then
    echo "Error params format, try: ftp_download HOST USER PASSWORD PATH BACKUP_DIR"
    exit 1
fi

host=$1
user=$2
password=$3
path=$4
bk_dir=$5
port=21

cd ${bk_dir}
#scp -P 22 ${user}@${host}:/${filename} ${bk_dir}
curl -O -u ${user}:${password} ftp://${host}:${port}/${path}
#wget -с --ftp-user=${user} --ftp-password=${password} ftp://${host}:${port}/${filename} -O - | tar -x -C ${bk_dir}
#ftp -in -u ftp://${user}:${password}@${host}:${port}/${filename} | tar -x -C ${bk_dir}