#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Error params format, try: my80_createdb DATABASE"
    exit 1
fi

dir=$(dirname $(readlink -e $0))

bash ${dir}/cli mysql80 "mysql -u \${MYSQL_USER} -p\${MYSQL_PASSWORD} -e \"CREATE DATABASE $1;\""