#!/usr/bin/env bash

set -euo pipefail

dir=$(dirname $(readlink -e $0))

if [ $# -ne 0 ]; then
    bash ${dir}/cmd mysql "mysql -u \${MYSQL_USER} -p\${MYSQL_PASSWORD} -e \"$*;\""
else
    bash ${dir}/cmd mysql "mysql -u \${MYSQL_USER} -p\${MYSQL_PASSWORD}"
fi