#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Error params format, try: pg_createdb DATABASE"
    exit 1
fi

dir=$(dirname $(readlink -e $0))

bash ${dir}/cmd postgres "psql -U \${POSTGRES_USER} -c \"CREATE DATABASE $1;\""