#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Error params format, try: pg_import DATABASE [FILE]"
    exit 1
fi

if [ $# -eq 1 ]; then
    file="$1.sql"
else
    file=$2
fi

dir=$(dirname $(readlink -e $0))

bash ${dir}/pg_dropdb $1
bash ${dir}/pg_createdb $1
bash ${dir}/cmd postgres "cd /var/lib/postgresql/backup && psql -d $1 -U \${POSTGRES_USER} -f $file"