#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Error params format, try: pg_restore DATABASE [FILE]"
    exit 1
fi

if [ $# -eq 1 ]; then
    file="$1.gz"
else
    file=$2
fi

dir=$(dirname $(readlink -e $0))

bash ${dir}/cli postgres "cd /var/lib/postgresql/backup && pg_restore -c -d $1 -U \${POSTGRES_USER} -j 8 $file"