#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Error params format, try: php-cli PROJECT COMMAND [OPTIONS]"
    exit 1
fi

dir=$(dirname $(readlink -e $0))

project=$1

shift

bash ${dir}/cli php-cli $project "$*"